### ISSUE TITLE
Getting when generating preview JSON::ParserError

### ISSUE THREAD

**Issue by haggen** [jonahoffline/filepreviews-ruby#8]
Just by calling `Filepreviews.generate` I'm getting `JSON::ParserError`; see the trace below.

```
json (1.8.2) lib/json/common.rb:155:in `initialize'
json (1.8.2) lib/json/common.rb:155:in `new'
json (1.8.2) lib/json/common.rb:155:in `parse'
filepreviews (1.2.0) lib/filepreviews/http.rb:69:in `parse'
filepreviews (1.2.0) lib/filepreviews/http.rb:62:in `fetch'
filepreviews (1.2.0) lib/filepreviews.rb:20:in `generate'
actionpack (3.2.21) lib/action_view/template.rb:145:in `block in render'
activesupport (3.2.21) lib/active_support/notifications.rb:125:in `instrument'
actionpack (3.2.21) lib/action_view/template.rb:143:in `render'
actionpack (3.2.21) lib/action_view/renderer/template_renderer.rb:47:in `block (2 levels) in render_template'
actionpack (3.2.21) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
activesupport (3.2.21) lib/active_support/notifications.rb:123:in `block in instrument'
activesupport (3.2.21) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (3.2.21) lib/active_support/notifications.rb:123:in `instrument'
actionpack (3.2.21) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
actionpack (3.2.21) lib/action_view/renderer/template_renderer.rb:46:in `block in render_template'
actionpack (3.2.21) lib/action_view/renderer/template_renderer.rb:54:in `render_with_layout'
actionpack (3.2.21) lib/action_view/renderer/template_renderer.rb:45:in `render_template'
actionpack (3.2.21) lib/action_view/renderer/template_renderer.rb:18:in `render'
actionpack (3.2.21) lib/action_view/renderer/renderer.rb:36:in `render_template'
actionpack (3.2.21) lib/action_view/renderer/renderer.rb:17:in `render'
actionpack (3.2.21) lib/abstract_controller/rendering.rb:110:in `_render_template'
actionpack (3.2.21) lib/action_controller/metal/streaming.rb:225:in `_render_template'
actionpack (3.2.21) lib/abstract_controller/rendering.rb:103:in `render_to_body'
actionpack (3.2.21) lib/action_controller/metal/renderers.rb:28:in `render_to_body'
actionpack (3.2.21) lib/action_controller/metal/compatibility.rb:50:in `render_to_body'
actionpack (3.2.21) lib/abstract_controller/rendering.rb:88:in `render'
actionpack (3.2.21) lib/action_controller/metal/rendering.rb:16:in `render'
actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:40:in `block (2 levels) in render'
activesupport (3.2.21) lib/active_support/core_ext/benchmark.rb:5:in `block in ms'
/usr/local/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
activesupport (3.2.21) lib/active_support/core_ext/benchmark.rb:5:in `ms'
actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:40:in `block in render'
actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:83:in `cleanup_view_runtime'
actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:39:in `render'
actionpack (3.2.21) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
actionpack (3.2.21) lib/action_controller/metal/implicit_render.rb:5:in `send_action'
actionpack (3.2.21) lib/abstract_controller/base.rb:167:in `process_action'
actionpack (3.2.21) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (3.2.21) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
activesupport (3.2.21) lib/active_support/callbacks.rb:436:in `_run__1199963992045643328__process_action__354792127446437228__callbacks'
activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `__run_callback'
activesupport (3.2.21) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
activesupport (3.2.21) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.2.21) lib/abstract_controller/callbacks.rb:17:in `process_action'
actionpack (3.2.21) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
activesupport (3.2.21) lib/active_support/notifications.rb:123:in `block in instrument'
activesupport (3.2.21) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (3.2.21) lib/active_support/notifications.rb:123:in `instrument'
actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
actionpack (3.2.21) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
actionpack (3.2.21) lib/abstract_controller/base.rb:121:in `process'
actionpack (3.2.21) lib/abstract_controller/rendering.rb:45:in `process'
actionpack (3.2.21) lib/action_controller/metal.rb:203:in `dispatch'
actionpack (3.2.21) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
actionpack (3.2.21) lib/action_controller/metal.rb:246:in `block in action'
actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:73:in `call'
actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:36:in `call'
journey (1.0.4) lib/journey/router.rb:68:in `block in call'
journey (1.0.4) lib/journey/router.rb:56:in `each'
journey (1.0.4) lib/journey/router.rb:56:in `call'
actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:608:in `call'
mongoid (3.1.6) lib/rack/mongoid/middleware/identity_map.rb:34:in `block in call'
mongoid (3.1.6) lib/mongoid/unit_of_work.rb:39:in `unit_of_work'
mongoid (3.1.6) lib/rack/mongoid/middleware/identity_map.rb:34:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
rack (1.4.5) lib/rack/etag.rb:23:in `call'
rack (1.4.5) lib/rack/conditionalget.rb:25:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/head.rb:14:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/flash.rb:242:in `call'
rack (1.4.5) lib/rack/session/abstract/id.rb:210:in `context'
rack (1.4.5) lib/rack/session/abstract/id.rb:205:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/cookies.rb:341:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `_run__2601463367027478767__call__4555912327375473480__callbacks'
activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `__run_callback'
activesupport (3.2.21) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
activesupport (3.2.21) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.2.21) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/reloader.rb:65:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
better_errors (2.1.1) lib/better_errors/middleware.rb:59:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
railties (3.2.21) lib/rails/rack/logger.rb:32:in `call_app'
railties (3.2.21) lib/rails/rack/logger.rb:16:in `block in call'
activesupport (3.2.21) lib/active_support/tagged_logging.rb:22:in `tagged'
railties (3.2.21) lib/rails/rack/logger.rb:16:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/request_id.rb:22:in `call'
rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
rack (1.4.5) lib/rack/runtime.rb:17:in `call'
activesupport (3.2.21) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
rack (1.4.5) lib/rack/lock.rb:15:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/static.rb:83:in `call'
rack-timeout (0.2.0) lib/rack/timeout.rb:108:in `call'
railties (3.2.21) lib/rails/engine.rb:484:in `call'
railties (3.2.21) lib/rails/application.rb:231:in `call'
railties (3.2.21) lib/rails/railtie/configurable.rb:30:in `method_missing'
rack (1.4.5) lib/rack/deflater.rb:13:in `call'
rack-cors (0.3.1) lib/rack/cors.rb:72:in `call'
rack (1.4.5) lib/rack/content_length.rb:14:in `call'
railties (3.2.21) lib/rails/rack/log_tailer.rb:17:in `call'
thin (1.6.3) lib/thin/connection.rb:86:in `block in pre_process'
thin (1.6.3) lib/thin/connection.rb:84:in `catch'
thin (1.6.3) lib/thin/connection.rb:84:in `pre_process'
thin (1.6.3) lib/thin/connection.rb:53:in `process'
thin (1.6.3) lib/thin/connection.rb:39:in `receive_data'
eventmachine (1.0.7) lib/eventmachine.rb:187:in `run_machine'
eventmachine (1.0.7) lib/eventmachine.rb:187:in `run'
thin (1.6.3) lib/thin/backends/base.rb:73:in `start'
thin (1.6.3) lib/thin/server.rb:162:in `start'
rack (1.4.5) lib/rack/handler/thin.rb:13:in `run'
rack (1.4.5) lib/rack/server.rb:268:in `start'
railties (3.2.21) lib/rails/commands/server.rb:70:in `start'
railties (3.2.21) lib/rails/commands.rb:55:in `block in <top (required)>'
railties (3.2.21) lib/rails/commands.rb:50:in `tap'
railties (3.2.21) lib/rails/commands.rb:50:in `<top (required)>'
script/rails:6:in `require'
script/rails:6:in `<main>'
```

**Comment by haggen** [comment]
The same error happens when using the CLI. Please note that I'm trying to run it from inside a Docker container running on Debian "jessie". If a component or library is missing, it should have complained, shouldn't it ?

**Comment by jonahoffline** [comment]
@haggen sorry I didn't see this sooner. I just tried to reproduce this on my box with no success. Can you share your `Dockerfile` (or anything else like ruby version, etc).

**Comment by jpadilla** [comment]
This is part implementation issue on all v1 client libraries which did
polling for results and hanged previews on our side. Implementation of v2
libraries remove this behavior by default.

**Comment by jonahoffline** [comment]
@jpadilla my implementation of `v1` doesn't poll for results (first request only returns image and metadata urls; for metadata you have to call the method).

**Comment by haggen** [comment]
The image I'm using is this https://registry.hub.docker.com/u/haggen/rails/dockerfile/ which is based on this https://registry.hub.docker.com/u/haggen/ruby/dockerfile/.
